# $OpenBSD$

COMMENT =		Python 2.7 backport of the dis module from Python 3.5+

MODPY_EGG_VERSION =	0.1.2
DISTNAME =		dis3-${MODPY_EGG_VERSION}
PKGNAME =		py-${DISTNAME}
CATEGORIES =		devel

HOMEPAGE =		https://pypi.org/project/dis3

# Python
PERMIT_PACKAGE_CDROM =	Yes

MODULES =		lang/python

MODPY_PI =		Yes
MODPY_SETUPTOOLS =	Yes

.include <bsd.port.mk>
